### ISSUE TITLE
"<lambda or free run script>" script perf warning

### ISSUE THREAD

**Issue by GrinlexGH** [misyltoad/riscv-vscript#1]
I can't use riscv script because script perf warning
![image](https://github.com/Joshua-Ashton/riscv-vscript/assets/77984877/05f08279-2d74-4da7-8d23-43cb209503bf)

**Comment by misyltoad** [comment]
There is a convar you can increase to stop this printing. Try find script and look for it in the console.

**Comment by GrinlexGH** [comment]
I found it. It was the `vscript_perf_warning_spew_ms` and now it works, Thanks!
